server:
  port: 8081
## MQTT
mqtt:
  host: tcp://127.0.0.1:1883
  userName: admin
  passWord: abc456258ac00
  qos: 1
  clientId: serve
  timeout: 10
  keepalive: 20
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 10
      jedis:
        pool:
          max-active: 50
          max-wait: 3000ms
          max-idle: 20
          min-idle: 5
      connect-timeout: 5000ms
